# -*- coding: utf-8 -*-
"""Copy of  Hardware_train_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUaOmBxo5Pz91T32N1lsw4Vm8a70KcfU
"""

# Import the necessary module to interact with Google Drive.
from google.colab import drive

# Mount Google Drive to the specified path.
drive.mount('/content/drive')

"""# UTILS"""

import numpy as np
import torch
from scipy.interpolate import interp1d
from scipy.stats import truncnorm
import pickle as pkl


import numpy as np
import torch

class sigGen():
    def __init__(self, config):
        self.inLen = config["inputLength"]
        self.outLen = config["outputLength"]

        # Remove dataset loading, just initialize empty placeholders
        self.pool = []  # No preloaded signals
        self.offduration = []  # No predefined off durations

    def getSignal(self, appNum, length):
        # Instead of fetching stored signals, generate a random signal of desired length
        sigCh = np.random.rand(length) * 100  # Replace with actual signal from your dataset if available
        y_of_ori = np.ones_like(sigCh)

        signal = torch.from_numpy(sigCh)
        signal_scaled = signal / 612  # Normalize

        y_of = torch.from_numpy(y_of_ori)
        return signal_scaled, signal, y_of

def vertScale2(x):
    # scale = np.random.uniform(0.8, 1.2, 1)
    mu, sigma = 1, 0.2
    lower, upper = mu - 2*sigma, mu + 2*sigma
    tn = truncnorm((lower - mu) / sigma, (upper - mu) / sigma, loc=mu, scale=sigma)
    scale = tn.rvs(1)
    return x*torch.from_numpy(scale)

def horiScale2(input):
    olength = int(len(input)/2)
    # scale = np.random.uniform(0.8, 1.2, 1)
    mu, sigma = 1, 0.2
    lower, upper = mu - 2*sigma, mu + 2*sigma
    tn = truncnorm((lower - mu) / sigma, (upper - mu) / sigma, loc=mu, scale=sigma)
    scale = tn.rvs(1)
    y = input.reshape(-1)
    x = np.arange(0, len(y))
    f = interp1d(x, y)

    xnew = np.arange(0, len(y) - 1, scale)
    ynew = f(xnew)
    if len(ynew) > olength:
        return torch.from_numpy(ynew[:olength])
    else:
        diffSize = olength - len(ynew)
        ynew = np.pad(ynew, (0, diffSize), 'constant')
        return torch.from_numpy(ynew)


def insertSig(sig, length, config, start_index):
    signal = torch.zeros(length)
    if start_index < 0:
        signal[:min(len(sig) + start_index, length)] = sig[-start_index:min(len(sig), length - start_index)]
    else:
        signal[start_index:min(len(sig) + start_index, length)] = sig[:min(len(sig), length - start_index)]

    return signal

def selectPortion(config, sig, length):
    insertIdxLrange = int((config["inputLength"] - config["outputLength"])/2) - len(sig)
    insertIdxRrange = int((config["inputLength"] + config["outputLength"])/2)
    idx = np.random.randint(insertIdxLrange, insertIdxRrange)
    signal = insertSig(sig, length, config, idx)
    # y_of = torch.where(signal > 15/612, torch.Tensor([1]), torch.Tensor([0]))
    return signal

def dataAug( X_scaled, Y_scaled, Y_of, sigClass, config):
    orilen = Y_scaled.shape[-1]
    prob=[config["prob0"], config["prob1"], config["prob2"], config["prob3"]]
    xlen = len(sigClass.pool) - orilen
    prob.extend([0.1] * xlen)
    llen = Y_scaled.shape[1]

    # prob=[config.prob0, config.prob1, config.prob2]
    for i in range(X_scaled.shape[0]):
        minX = min(X_scaled[i,:,0]).item()
        for j in range(len(prob)):
            # onOff = sum(Y_of[i,:,j])
            p = np.random.rand(1)
            if p < prob[j]: # do data_aug
                if j < orilen:
                    X_scaled[i,:,0] -= Y_scaled[i,:,j]
                    Y_scaled[i, :, j] -= Y_scaled[i,:,j]
                sig, sig_ori, y_of = sigClass.getSignal(j, Y_scaled.shape[1]*2)

                if j==0:
                    mode = np.random.choice(4, 1, p=[.25, .25, .25, .25])
                elif j==1:
                    mode = np.random.choice(4, 1, p=[.25, .25, .25, .25])
                else:
                    mode = np.random.choice(4, 1, p=[.25, .25, .25, .25])
                ## 0: origin, 1:vertical scaled, 2: horizon scaled, 3: v&h scaled
                if mode == 1:
                    sig = vertScale2(sig)

                elif mode == 2:
                    sig = horiScale2(sig)

                elif mode == 3:
                    sig = horiScale2(sig)
                    sig = vertScale2(sig)

                sig = selectPortion(config, sig, llen)
                y_of = torch.where(sig > 15/612, torch.Tensor([1]), torch.Tensor([0]))
                if j < orilen:
                    Y_scaled[i,:,j] += sig
                    Y_of[i, :, j] = y_of
                X_scaled[i,:,0] += sig

    return X_scaled, Y_scaled, Y_of

"""DATASET"""

import os
import pandas as pd
import pickle as pkl
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader, Sampler
import numpy as np

class Blank_Dataset(Dataset):
    def __init__(self): #input here
        # store here
        pass
    def __getitem__(self, index):
        # process batch here
        pass
    def __len__(self):
        # total size of the dataset
        pass

class testSampler(Sampler):
    r"""Samples elements sequentially, always in the same order.

    Args:
        data_source (Dataset): dataset to sample from
    """

    def __init__(self, length, step):
        self.length = length
        self.step = step

    def __iter__(self):
        return iter(range(0,self.length,self.step))

    def __len__(self) -> int:
        return len(range(0,self.length,self.step))

class SubSet(Dataset):
    def __init__(self, x, length_input=400, length_output=400):
        super().__init__()
        self.outputs = x[:, 3:]
        self.mains = x[:, :3]
        self.inLen = length_input
        self.outLen = length_output

    def __getitem__(self, index):
        in_begin = index
        in_end = in_begin + self.inLen
        # out_begin = in_begin + int((self.inLen-self.outLen)/2)
        # out_end = out_begin + self.outLen

        X = self.mains[in_begin:in_end,:]
        # Y = self.outputs[out_begin:out_end,:]
        Y = self.outputs[in_begin:in_end,:]

        X_scaled = X/612
        Y_scaled = Y/612
        Y_of = np.where(Y > 15, 1, 0)

        return X, Y, X_scaled, Y_scaled, Y_of

    def __len__(self):
        return len(self.outputs)-self.inLen + 1

if __name__ == '__main__':
    path = "/content/drive/MyDrive/Data/All_Hardware_xlsx/split_data"
    train_arrays = pkl.load(open(os.path.join(path,"merged_2345.pkl"),'rb')) # 1 household

    # Use train_arrays directly instead of train_arrays.values
    train_dataset = SubSet(train_arrays)

    X, Y, X_scaled, Y_scaled, Y_of = train_dataset[0]


    train_Dataloader = DataLoader(
                            train_dataset,
                            batch_size=64,
                            #sampler=train_subsampler,
                            num_workers=0,
                            #pin_memory=True
                            )
    for i, batch in enumerate(train_Dataloader):
        X, Y, X_scaled, Y_scaled, Y_of = batch
        break

"""MODELS"""

import torch
import torch.nn as nn

class ApplSA(nn.Module):
    def __init__(self, config, LSTM=False, splitLoss=False):
        super().__init__()
        self.self_attn = nn.MultiheadAttention(2*config["hidden"], 2, batch_first=True)
        d_model = 2*config["hidden"]
        dim_feedforward = 1024
        dropout = config["dropout"]
        self.dropout = nn.Dropout(dropout)
        self.norm1 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout)

    def _sa_block(self, x):
        x = self.self_attn(x, x, x)[0]
        return self.dropout1(x)

    def forward(self, x):
        x = self.norm1(x + self._sa_block(x))
        return x

class ApplFF(nn.Module):
    def __init__(self, config, LSTM=False, splitLoss=False):
        super().__init__()
        d_model = 2*config["hidden"]
        dim_feedforward = 1024
        dropout = config["dropout"]
        self.dropout = nn.Dropout(dropout)
        self.linear1 = nn.Linear(d_model, dim_feedforward)
        self.linear2 = nn.Linear(dim_feedforward, d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout2 = nn.Dropout(dropout)

    def _ff_block(self, x):
        x = self.linear2(self.dropout(torch.relu(self.linear1(x))))
        return self.dropout2(x)

    def forward(self, x):
        x = self.norm2(x + self._ff_block(x))
        return x

class ApplBlock(nn.Module):
    def __init__(self, config, Last=False, LSTM=False, splitLoss=False):
        super().__init__()
        self.multihead_attn_d = ApplSA(config)
        self.multihead_attn_f = ApplSA(config)
        self.multihead_attn_m = ApplSA(config)
        self.multihead_attn_w = ApplSA(config)

        self.multihead_attn_r_g = nn.MultiheadAttention(2*config["hidden"], 2, batch_first=True)
        self.norm1 = nn.LayerNorm(2*config["hidden"])

        self.dish = ApplFF(config)
        self.frid = ApplFF(config)
        self.micro = ApplFF(config)
        self.wash = ApplFF(config)
        self.Last = Last
        if Last:
            self.dish_c = ApplFF(config)
            self.frid_c = ApplFF(config)
            self.micro_c = ApplFF(config)
            self.wash_c = ApplFF(config)

    def forward(self, d_r_a, f_r_a, m_r_a, w_r_a):
        attn_output_d = self.multihead_attn_d(d_r_a)
        attn_output_f = self.multihead_attn_f(f_r_a)
        attn_output_m = self.multihead_attn_m(m_r_a)
        attn_output_w = self.multihead_attn_w(w_r_a)

        GlobleAtten_r = torch.cat((attn_output_d.unsqueeze(3), attn_output_f.unsqueeze(3), attn_output_m.unsqueeze(3), attn_output_w.unsqueeze(3)),3)
        GlobleAtten_r = GlobleAtten_r.permute(0,1,3,2)
        # TODO: change 4
        GlobleAtten_r = GlobleAtten_r.reshape(-1,4,GlobleAtten_r.shape[-1])

        # # Globle attention
        attn_output_r_g, attn_output_weights_r_g = self.multihead_attn_r_g(GlobleAtten_r,GlobleAtten_r,GlobleAtten_r)
        # TODO: change 4
        attn_output_r_g = attn_output_r_g.reshape(d_r_a.shape[0],d_r_a.shape[1],4,GlobleAtten_r.shape[-1])

        d_r_a = attn_output_r_g[:,:,0,:]
        f_r_a = attn_output_r_g[:,:,1,:]
        m_r_a = attn_output_r_g[:,:,2,:]
        w_r_a = attn_output_r_g[:,:,3,:]

        d_r_a = self.norm1(d_r_a + attn_output_d)
        f_r_a = self.norm1(f_r_a + attn_output_f)
        m_r_a = self.norm1(m_r_a + attn_output_m)
        w_r_a = self.norm1(w_r_a + attn_output_w)

        d_r = self.dish(d_r_a)
        f_r = self.frid(f_r_a)
        m_r = self.micro(m_r_a)
        w_r = self.wash(w_r_a)

        if self.Last:
            d_c = self.dish_c(d_r_a)
            f_c = self.frid_c(f_r_a)
            m_c = self.micro_c(m_r_a)
            w_c = self.wash_c(w_r_a)
            return d_r, f_r, m_r, w_r, d_c, f_c, m_c, w_c

        return d_r, f_r, m_r, w_r


class MATconv(nn.Module):
    def __init__(self, config, LSTM=False, splitLoss=False):
        super().__init__()
        self.input_size = config["input_size"]
        self.sharedLayer = nn.Sequential(

            nn.Conv1d(3, 30, kernel_size=10, padding='same'),
            nn.ReLU(True),
            #nn.Conv1d(30, 30, kernel_size=8, padding='same'),
            #nn.ReLU(True),
            #nn.Conv1d(30, 40, kernel_size=6, padding='same'),
            #nn.ReLU(True),
            nn.Conv1d(30, 50, kernel_size=5, padding='same'),
            nn.ReLU(True),
            nn.Conv1d(50, 50, kernel_size=5, padding='same'),
            nn.ReLU(True),
            nn.Conv1d(50, int(config["hidden"]*2), kernel_size=5, padding='same'),
            nn.ReLU(True)
        )

        self.block1 = ApplBlock(config)
        self.block2 = ApplBlock(config)
        self.block3 = ApplBlock(config,Last=True)


        self.fc_dr = nn.Sequential(nn.Linear(2*config["hidden"], config["hidden"]),
                                   nn.ReLU(),
                                   nn.Linear(config["hidden"], 1))
        self.fc_dc = nn.Sequential(nn.Linear(2*config["hidden"], config["hidden"]),
                                   nn.ReLU(),
                                   nn.Linear(config["hidden"], 1))
        self.fc_fr = nn.Sequential(nn.Linear(2*config["hidden"], config["hidden"]),
                                   nn.ReLU(),
                                   nn.Linear(config["hidden"], 1))
        self.fc_fc = nn.Sequential(nn.Linear(2*config["hidden"], config["hidden"]),
                                   nn.ReLU(),
                                   nn.Linear(config["hidden"], 1))
        self.fc_mr = nn.Sequential(nn.Linear(2*config["hidden"], config["hidden"]),
                                   nn.ReLU(),
                                   nn.Linear(config["hidden"], 1))
        self.fc_mc = nn.Sequential(nn.Linear(2*config["hidden"], config["hidden"]),
                                   nn.ReLU(),
                                   nn.Linear(config["hidden"], 1))

        self.fc_wr = nn.Sequential(nn.Linear(2*config["hidden"], config["hidden"]),
                                   nn.ReLU(),
                                   nn.Linear(config["hidden"], 1))
        self.fc_wc = nn.Sequential(nn.Linear(2*config["hidden"], config["hidden"]),
                                   nn.ReLU(),
                                   nn.Linear(config["hidden"], 1))

    def forward(self, input_data):

        # feature weighting
        # attn_weights = torch.softmax(self.attn_layer(input_data), 2)
        # weighted_input = torch.mul(attn_weights, input_data)
        # skip_x =
        # self.sharedLayer.flatten_parameters()
        input_data = input_data.permute(0,2,1)
        input_encoded = self.sharedLayer(input_data)  # input(1, batch_size, input_size)
        input_encoded = input_encoded.permute(0,2,1)
        # print(input_encoded.shape)
        # print(input_encoded.shape)
        # print(input_data.shape)
        # input_encoded = self.norm(input_encoded + self.skipExpand(input_data))

        # Attention
        d_r, f_r, m_r, w_r = self.block1(input_encoded, input_encoded, input_encoded, input_encoded)
        d_r, f_r, m_r, w_r = self.block2(d_r, f_r, m_r, w_r)
        d_rr, f_rr, m_rr, w_rr, d_cc, f_cc, m_cc, w_cc = self.block3(d_r, f_r, m_r, w_r)

        dc = torch.sigmoid(self.fc_dc(d_cc))
        fc = torch.sigmoid(self.fc_fc(f_cc))
        mc = torch.sigmoid(self.fc_mc(m_cc))
        wc = torch.sigmoid(self.fc_wc(w_cc))

        # dr = torch.relu(self.fc_dr(d_rr)) * dc
        # fr = torch.relu(self.fc_fr(f_rr)) * fc
        # mr = torch.relu(self.fc_mr(m_rr)) * mc
        # wr = torch.relu(self.fc_wr(w_rr)) * wc

        dr = self.fc_dr(d_rr) * dc
        fr = self.fc_fr(f_rr) * fc
        mr = self.fc_mr(m_rr) * mc
        wr = self.fc_wr(w_rr) * wc

        y_pred_r = torch.cat((dr,fr,mr, wr),2)
        y_pred_c = torch.cat((dc,fc,mc, wc),2)
        # print(y_pred_r.shape)
        return y_pred_r, y_pred_c
'''
if __name__ == '__main__':
    config_dict = {
        "input_size": 1,
        "batch_size": 32, #batch size
        "lr": 0.001, #learning rate
        "hidden": 32, #encoder decoder hidden size
        "dropout": 0.1, #dropout
        "outputLength": 864, #output length for the model
        "inputLength" : 864, #input length for the model
        "dataAug": True,
        "prob0": 0.3, #augment probability for Dishwasher
        "prob1": 0.6,
        "prob2": 0.3,
        "prob3": 0.3,
    }
    inp = torch.rand([32, 864, 1])
    model = MATconv(config_dict)
    y_pred_r, y_pred_c = model(inp)
    '''

"""TRAINER CALLBACKS"""

from tqdm import tqdm
import numpy as np
import os
import torch
import random

def set_random_state(seed_value: int):
    os.environ['PYTHONHASHSEED'] = str(seed_value)
    random.seed(seed_value)
    np.random.seed(seed_value)
    torch.manual_seed(seed_value)
    torch.cuda.manual_seed(seed_value)
    torch.cuda.manual_seed_all(seed_value)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.random.manual_seed(seed_value)

class ProgressBar():
    def __init__(self, steps: int, description:str = None):
        '''initiate the progbar with total steps, optional: set description'''
        self.steps = steps
        self.description = description
        self.progbar = tqdm(total=self.steps, unit=' steps')
        self.progbar.set_description(description)
    def update(self, increment_count=None, logs_to_display: dict = None):
        '''increment counter, update displayed info'''
        if logs_to_display is not None:
            logs_to_display = {key: '%.06f' % logs_to_display[key] for key in logs_to_display.keys()}
            self.progbar.set_postfix(logs_to_display)
        if increment_count is not None:
            self.progbar.update(increment_count)
    def close(self, logs_to_display: dict = None):
        '''close the progbar, optional: update displayed info'''
        if logs_to_display is not None:
            logs_to_display = {key: '%.06f' % logs_to_display[key] for key in logs_to_display.keys()}
            self.progbar.set_postfix(logs_to_display)
        self.progbar.close()

class AverageMeter():
    def __init__(self):
        self.reset()
    def reset(self):
        self.avg = 0
        self.sum = 0
        self.count = 0
    def update(self, inp: list):
        score = inp[0]
        n = inp[1]
        self.sum += score * n
        self.count += n
        self.avg = self.sum / self.count
    def feedback(self):
        return self.avg

class PrintMeter():
    def __init__(self):
        self.reset()
    def reset(self):
        self.value = 0
    def update(self, inp):
        self.value = inp
    def feedback(self):
        return self.value

class MetricStoreBox():
    def __init__(self, metrics:dict):
        self.metrics = metrics
        self.metric_functions = {}
        for key in metrics.keys():
            self.metric_functions.update({key:metrics[key]()})
    def update(self, info_dict:dict):
        for key in info_dict.keys():
            self.metric_functions[key].update(info_dict[key])
    def get_value(self):
        logs = {}
        for key in self.metrics.keys():
            logs.update({key:self.metric_functions[key].feedback()})
        return logs

"""TRAINER"""

import os
import torch
from torch import nn
#from trainer_callbacks import MetricStoreBox, ProgressBar

import numpy as np
#from utils import sigGen, dataAug

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

def check_if_best_value(current_value: float, previous_best_value: float, metric_name: str='loss', mode: str='min', verbose: bool=True):
    if mode == 'min':
        if previous_best_value > current_value:
            if verbose:
                print('\033[32;1m' + ' Val {} is improved from {:.4f} to {:.4f}! '.format(metric_name, previous_best_value, current_value) + '\033[0m')
            best_value = current_value
            is_best_value = True
        else:
            if verbose:
                print('\033[31;1m' + ' Val {} is not improved from {:.4f}! '.format(metric_name, previous_best_value) + '\033[0m')
            best_value = previous_best_value
            is_best_value = False
    else:
        if previous_best_value < current_value:
            if verbose:
                print('\033[32;1m' + ' Val {} is improved from {:.4f} to {:.4f}! '.format(metric_name, previous_best_value, current_value) + '\033[0m')
            best_value = current_value
            is_best_value = True
        else:
            if verbose:
                print('\033[31;1m' + ' Val {} is not improved from {:.4f}! '.format(metric_name, previous_best_value) + '\033[0m')
            best_value = previous_best_value
            is_best_value = False

    return best_value, is_best_value

#%% #################################### Model Trainer Class ####################################
class ModelTrainer():
    def __init__(self,
                 model: torch.nn.Module,
                 Loaders: list,
                 metrics: dict,
                 lr: float,
                 epochsTorun: int,
                 checkpoint_saving_path: str,
                 fold: int,
                 debug: bool,
                 perform_dataAug: bool,
                 config_dict: dict,
                 ):
        super().__init__()

        self.metrics = metrics
        self.model = model.to(DEVICE)
        self.trainLoader = Loaders[0]
        self.valLoader = Loaders[1]

        self.fold = fold
        if self.fold != None:
            self.checkpoint_saving_path = checkpoint_saving_path + '/fold' + str(self.fold) + '/'
        else:
            self.checkpoint_saving_path = checkpoint_saving_path + '/'
        os.makedirs(self.checkpoint_saving_path,exist_ok=True)

        self.lr = lr
        self.epochsTorun = epochsTorun

        self.best_loss = 9999
        self.optimizer = torch.optim.Adam(params=[p for p in self.model.parameters() if p.requires_grad], lr=self.lr)
        self.scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(self.optimizer, mode='min', factor=0.5, patience=10)

        self.all_logs = {}
        self.criterion_reg = nn.MSELoss()
        self.criterion_cls = nn.BCELoss()

        self.debug = debug
        self.perform_dataAug = perform_dataAug
        self.config_dict = config_dict
        if perform_dataAug:
            self.sigClass = sigGen(config_dict)

    def get_checkpoint(self, val_logs):
        checkpoint_dict = {
            'Epoch': self.current_epoch_no,
            'Model_state_dict': self.model.state_dict(),
            'Optimizer_state_dict': self.optimizer.state_dict(),
            }

        for key in val_logs.keys():
            checkpoint_dict.update({key: val_logs[key]})

        return checkpoint_dict

    def perform_validation(self, use_progbar: bool=True, best_metric_verbose: bool=True):
        self.model.eval()
        torch.set_grad_enabled(False)
        val_info_box = MetricStoreBox(self.metrics)

        if use_progbar:
            if self.fold == None:
                progbar_description = f'(val) Epoch {self.current_epoch_no}/{self.epochsTorun}'
            else:
                progbar_description = f'(val) Fold {self.fold} Epoch {self.current_epoch_no}/{self.epochsTorun}'
            val_progbar = ProgressBar(len(self.valLoader), progbar_description)

        for itera_no, data in enumerate(self.valLoader):
            _, _, X_scaled, Y_scaled, Y_of = data

            X_scaled = X_scaled.float().to(DEVICE)
            Y_scaled = Y_scaled.float().to(DEVICE)
            Y_of = Y_of.float().to(DEVICE)

            # get model predictions
            y_pred_r, y_pred_c = self.model(X_scaled)

            # calculate loss
            loss_r = self.criterion_reg(y_pred_r,Y_scaled)
            loss_c = self.criterion_cls(y_pred_c, Y_of)
            batch_loss = loss_r + loss_c

            # update progress bar, info box
            val_info_box.update({
                'loss':[batch_loss.detach().item(), X_scaled.shape[0]],
                'reg_loss':[loss_r.detach().item(), X_scaled.shape[0]],
                'cls_loss':[loss_c.detach().item(), X_scaled.shape[0]]}
                )
            logs_to_display=val_info_box.get_value()
            logs_to_display = {f'val_{key}': logs_to_display[key] for key in logs_to_display.keys()}
            if use_progbar:
                val_progbar.update(1, logs_to_display)

        # calculate all metrics and close progbar
        logs_to_display=val_info_box.get_value()
        logs_to_display = {f'val_{key}': logs_to_display[key] for key in logs_to_display.keys()}

        val_logs = logs_to_display
        self.best_loss, is_best_loss = check_if_best_value(val_logs['val_loss'], self.best_loss, 'loss', 'min', best_metric_verbose)

        checkpoint_dict = self.get_checkpoint(val_logs)
        if is_best_loss:
            if self.fold == None:
                torch.save(checkpoint_dict, self.checkpoint_saving_path+'checkpoint_best_loss.pth')
            else:
                torch.save(checkpoint_dict, self.checkpoint_saving_path+'checkpoint_best_loss_fold{}.pth'.format(self.fold))

        if self.current_epoch_no % 10 == 0:
            if self.fold == None:
                torch.save(checkpoint_dict, self.checkpoint_saving_path+'checkpoint_epoch_{}.pth'.format(self.current_epoch_no))
            else:
                torch.save(checkpoint_dict, self.checkpoint_saving_path+'checkpoint_fold{}_epoch_{}.pth'.format(self.fold, self.current_epoch_no))

        del checkpoint_dict

        best_results_logs = {'best_val_loss':self.best_loss}
        logs_to_display.update(best_results_logs)
        if use_progbar:
            val_progbar.update(logs_to_display=logs_to_display)
            val_progbar.close()

        val_logs = logs_to_display
        return val_logs

    def train_one_epoch(self):
        train_info_box = MetricStoreBox(self.metrics)

        if self.fold == None:
            progbar_description = f'(Train) Epoch {self.current_epoch_no}/{self.epochsTorun}'
        else:
            progbar_description = f'(Train) Fold {self.fold} Epoch {self.current_epoch_no}/{self.epochsTorun}'
        train_progbar = ProgressBar(len(self.trainLoader), progbar_description)

        self.model.train()
        torch.set_grad_enabled(True)
        self.optimizer.zero_grad()

        for itera_no, data in enumerate(self.trainLoader):
            _, _, X_scaled, Y_scaled, Y_of = data

            if self.perform_dataAug:
                X_scaled, Y_scaled, Y_of = dataAug(X_scaled.clone(), Y_scaled.clone(), Y_of.clone(), self.sigClass, self.config_dict)

            X_scaled = X_scaled.float().to(DEVICE)
            Y_scaled = Y_scaled.float().to(DEVICE)
            Y_of = Y_of.float().to(DEVICE)

            # get model predictions
            y_pred_r, y_pred_c = self.model(X_scaled)

            # calculate loss
            loss_r = self.criterion_reg(y_pred_r,Y_scaled)
            loss_c = self.criterion_cls(y_pred_c, Y_of)
            batch_loss = loss_r + loss_c

            # backpropagation
            batch_loss.backward()
            self.optimizer.step()
            self.optimizer.zero_grad()

            # update progress bar, info box
            train_info_box.update({'loss':[batch_loss.detach().item(), X_scaled.shape[0]],
                                    'reg_loss':[loss_r.detach().item(), X_scaled.shape[0]],
                                    'cls_loss':[loss_c.detach().item(), X_scaled.shape[0]],
                                   })
            logs_to_display=train_info_box.get_value()
            logs_to_display = {f'train_{key}': logs_to_display[key] for key in logs_to_display.keys()}
            best_results_logs = {'best_val_loss':self.best_loss}
            logs_to_display.update(best_results_logs)
            train_progbar.update(1, logs_to_display)

            if self.debug:
                if itera_no == 20:
                    break

        # calculate all metrics and close progbar
        logs_to_display=train_info_box.get_value()
        logs_to_display = {f'train_{key}': logs_to_display[key] for key in logs_to_display.keys()}
        train_logs = logs_to_display
        best_results_logs = {'best_val_loss':self.best_loss}
        logs_to_display.update(best_results_logs)
        train_progbar.update(logs_to_display=logs_to_display)
        train_progbar.close()

        return train_logs

#%% train part starts here
    def fit(self):
        for epoch in range(self.epochsTorun):
            self.current_epoch_no = epoch+1

            # self.model.reset_temp_emb()
            train_logs = self.train_one_epoch()
            val_logs = self.perform_validation()

            self.scheduler.step(val_logs['best_val_loss'])

            self.all_logs.update({
                f'Epoch_{self.current_epoch_no}_train_logs': train_logs,
                f'Epoch_{self.current_epoch_no}_val_logs': val_logs,
                })
            np.save(self.checkpoint_saving_path+'all_logs.npy', self.all_logs)

"""MAIN"""

import numpy as np
import torch
from torch.utils.data import DataLoader, ConcatDataset

import os
import pickle as pkl
#from datasets import SubSet, testSampler
#from models import MATconv as MAT

#from trainer_callbacks import AverageMeter, set_random_state
#from trainer import ModelTrainer

if __name__ == '__main__':
    set_random_state(2024)

    ###################################################################################
    # define configs
    config_dict = {
        "input_size": 3,
        "batch_size": 32, #batch size
        "lr": 0.001, #learning rate
        "hidden": 64, #encoder decoder hidden size
        "dropout": 0.1, #dropout
        "outputLength": 864, #output length for the model
        "inputLength" : 864, #input length for the model
        "dataAug": True,
        "prob0": 0.3, #augment probability for Dishwasher
        "prob1": 0.6,
        "prob2": 0.3,
        "prob3": 0.3,

        'weight_saving_path': '/content/drive/MyDrive/Data/All_Hardware_xlsx/Weights after train',

        "epochs": 5,
        "num_workers": 2, #cpu core
        "debug": False,
        'perform_dataAug': True,
    }
    DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    ###################################################################################
    # define datasets and dataloader
    path = "/content/drive/MyDrive/Data/All_Hardware_xlsx/split_data"
    train_arrays = pkl.load(open(os.path.join(path,"merged_2345.pkl"),'rb'))
    val_arrays = pkl.load(open(os.path.join(path,"part_1.pkl"),'rb'))
    test_arrays = pkl.load(open(os.path.join(path,"New_Hardware_test.pkl"),'rb'))

    length_input = config_dict["inputLength"]
    length_output = config_dict["outputLength"]

    #ListTrain = [SubSet(array.values, length_input=length_input, length_output=length_output) for array in [train_arrays]]
    #ListVal = [SubSet(array.values, length_input=length_input, length_output=length_output) for array in [val_arrays]]
    #ListTest = [SubSet(array.values, length_input=length_input, length_output=length_output) for array in [test_arrays]]
    ListTrain = [SubSet(array, length_input=length_input, length_output=length_output) for array in [train_arrays]]  # Pass array directly
    ListVal = [SubSet(array, length_input=length_input, length_output=length_output) for array in [val_arrays.values]]  # Access values for DataFrame
    ListTest = [SubSet(array, length_input=length_input, length_output=length_output) for array in [test_arrays.values]]  # Access values for DataFrame

    train_dataset = ConcatDataset(ListTrain)
    val_dataset = ConcatDataset(ListVal)
    test_dataset = ConcatDataset(ListTest)

    index = np.arange(0,train_dataset.cumulative_sizes[-1])
    train_subsampler = torch.utils.data.SubsetRandomSampler(index)
    train_Dataloader = DataLoader(
        train_dataset,
        batch_size=config_dict["batch_size"],
        sampler=train_subsampler,
        num_workers=config_dict["num_workers"],
        pin_memory=True)

    sampler = testSampler(val_dataset.cumulative_sizes[-1], config_dict["outputLength"])
    sampler_test = testSampler(test_dataset.cumulative_sizes[-1], config_dict["outputLength"])

    vali_Dataloader = DataLoader(
        val_dataset,
        batch_size=config_dict["batch_size"],
        sampler=sampler,
        num_workers=config_dict["num_workers"],
        pin_memory=True)

    test_Dataloader = DataLoader(
        test_dataset,
        batch_size=config_dict["batch_size"],
        sampler=sampler_test,
        num_workers=config_dict["num_workers"],
        pin_memory=True)

    ###################################################################################
    # define model
    model = MATconv(config_dict).to(DEVICE)
    checkpoint_path = '/content/drive/MyDrive/FYDP_FINAL/weight/checkpoint_best_loss.pth'
    #print('loading checkpoint!')
    #checkpoint = torch.load(checkpoint_path)
    checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))
    #print('loss score: {:.4f}'.format(checkpoint['val_loss']))
    model.load_state_dict(checkpoint['Model_state_dict'])
    model.eval()


    ###################################################################################
    # train model
    trainer_args = {
            'model': model,
            'Loaders': [train_Dataloader, vali_Dataloader],
            'metrics': {
                'loss': AverageMeter,
                'reg_loss': AverageMeter,
                'cls_loss': AverageMeter,
                },
            'checkpoint_saving_path': config_dict["weight_saving_path"],
            'lr': config_dict["lr"],
            'epochsTorun': config_dict["epochs"],
            'fold': None,
            'debug': config_dict["debug"],
            'perform_dataAug': config_dict['perform_dataAug'],
            'config_dict': config_dict,
            }

    trainer = ModelTrainer(**trainer_args)
    trainer.fit()

"""# Test Scores"""

import numpy as np
import torch
from torch.utils.data import DataLoader, ConcatDataset

import os
import pickle as pkl
#from datasets import SubSet, testSampler
#from models import MATconv as MAT

#from trainer_callbacks import set_random_state
from sklearn.metrics import f1_score
import pandas as pd


def nde(true, pred):
    """Calculates the Normalized Disaggregation Error (NDE)."""
    # Convert inputs to numpy arrays if they are tensors
    true_np = true.numpy() if isinstance(true, torch.Tensor) else np.asarray(true)
    pred_np = pred.numpy() if isinstance(pred, torch.Tensor) else np.asarray(pred)

    numerator = np.sqrt(np.sum((true_np - pred_np)**2))
    denominator = np.sqrt(np.sum(true_np**2))
    return numerator / denominator if denominator != 0 else np.nan


def sae(true, pred, N):
    """Calculates the Static Aggregation Error (SAE)."""
    # Convert inputs to numpy arrays if they are tensors
    true_np = true.numpy() if isinstance(true, torch.Tensor) else np.asarray(true)
    pred_np = pred.numpy() if isinstance(pred, torch.Tensor) else np.asarray(pred)

    num_period = int(len(true_np) / N)
    diff = 0
    for i in range(num_period):
        diff += abs(np.sum(true_np[i * N: (i + 1) * N]) - np.sum(pred_np[i * N: (i + 1) * N]))
    return diff / (N * num_period)

def ape(true, pred):
    """Calculates the Absolute Percentage Error (APE) with handling for zero true values and capping."""
    # Convert inputs to numpy arrays if they are tensors
    true_np = true.numpy() if isinstance(true, torch.Tensor) else np.asarray(true)
    pred_np = pred.numpy() if isinstance(pred, torch.Tensor) else np.asarray(pred)

    # Calculate individual APE values
    individual_ape = np.zeros_like(true_np, dtype=float)
    non_zero_indices = true_np != 0
    zero_indices = true_np == 0

    # Calculate APE for non-zero true values
    individual_ape[non_zero_indices] = (np.abs(true_np[non_zero_indices] - pred_np[non_zero_indices]) / true_np[non_zero_indices]) * 100

    # Calculate APE for zero true values
    individual_ape[zero_indices] = np.abs(true_np[zero_indices] - pred_np[zero_indices]) * 100 # As per user's formula

    # Cap APE values at 150 if they exceed 200
    individual_ape[individual_ape > 1000] = 1000

    # Calculate the mean APE
    ape_score = np.mean(individual_ape)

    return ape_score

def energy_accuracy(true_values, pred_values, spike_threshold=5):
    """Calculates the Energy Accuracy, ignoring abnormal spikes."""
    true_np = np.array(true_values, dtype=float)
    pred_np = np.array(pred_values, dtype=float)

    # Handle abnormal spikes: if a true value is > spike_threshold × median(true),
    # treat it as abnormal and ignore it in accuracy calculation
    median_val = np.median(true_np[true_np > 0]) if np.any(true_np > 0) else 1
    spike_mask = true_np > (spike_threshold * median_val)

    # Mask for normal data points
    normal_mask = ~spike_mask

    # Total actual energy for normal points
    total_true = np.sum(true_np[normal_mask])

    if total_true == 0:
        return 0.0  # Avoid division by zero if no valid data

    # Absolute error sum
    total_error = np.sum(np.abs(true_np[normal_mask] - pred_np[normal_mask]))

    # Energy Accuracy
    accuracy = (1 - (total_error / total_true)) * 100

    return accuracy


def evaluate_score(y_real, y_predict, y_real_c, y_pred_c):
    """
    Calculates and returns evaluation scores: MAE, SAE, F1, Accuracy, NDE, APE, and Energy Accuracy.
    """
    # Convert inputs to numpy arrays if they are tensors
    y_real_np = y_real.numpy() if isinstance(y_real, torch.Tensor) else np.asarray(y_real)
    y_predict_np = y_predict.numpy() if isinstance(y_predict, torch.Tensor) else np.asarray(y_predict)
    y_real_c_np = y_real_c.numpy() if isinstance(y_real_c, torch.Tensor) else np.asarray(y_real_c)
    y_pred_c_np = y_pred_c.numpy() if isinstance(y_pred_c, torch.Tensor) else np.asarray(y_pred_c)

    maeScore = np.mean(np.abs(y_predict_np - y_real_np))
    SAE = sae(y_real_np, y_predict_np, 1200)  # Assuming N = 1200 for SAE calculation
    f1s = f1_score(y_real_c_np, np.round(y_pred_c_np))
    nde_score = nde(y_real_np, y_predict_np)
    ape_score = ape(y_real_np, y_predict_np)
    accuracy_score = 100 - ape_score
    energy_acc = energy_accuracy(y_real_np, y_predict_np) # Calculate energy accuracy

    # Calculate classification accuracy:
    correct_predictions = np.sum(np.round(y_pred_c_np) == y_real_c_np)
    total_predictions = len(y_real_c_np)
    classification_accuracy = (correct_predictions / total_predictions) * 100


    return maeScore, SAE, f1s, classification_accuracy, nde_score, ape_score, accuracy_score, energy_acc # Return energy accuracy

def evaluate_score_multi(y_real, y_predict, y_real_c, y_pred_c):
    """
    Calculates evaluation scores for multiple appliances.
    """
    listOfAppliance = ['dish washer', 'fridge', 'microwave', 'wash']
    all_maeScore = []
    all_SAE = []
    all_f1s = []
    all_nde = []
    all_classification_accuracy = []  # To store classification accuracy values
    all_ape = [] # To store APE values
    all_accuracy = [] # To store 100 - APE values
    all_energy_accuracy = [] # To store energy accuracy values


    # Convert inputs to numpy arrays if they are tensors
    y_real_np = y_real.numpy() if isinstance(y_real, torch.Tensor) else np.asarray(y_real)
    y_predict_np = y_predict.numpy() if isinstance(y_predict, torch.Tensor) else np.asarray(y_predict)
    y_real_c_np = y_real_c.numpy() if isinstance(y_real_c, torch.Tensor) else np.asarray(y_real_c)
    y_pred_c_np = y_pred_c.numpy() if isinstance(y_pred_c, torch.Tensor) else np.asarray(y_pred_c)


    for i in range(y_predict_np.shape[1]):
        maeScore, SAE_score, f1s, classification_accuracy, nde_score, ape_score, accuracy_score, energy_acc = evaluate_score( # Unpack energy accuracy
            y_real_np[:, i], y_predict_np[:, i], y_real_c_np[:, i], y_pred_c_np[:, i]
        )
        all_maeScore.append(maeScore)
        all_SAE.append(SAE_score)
        all_f1s.append(f1s)
        all_nde.append(nde_score)
        all_classification_accuracy.append(classification_accuracy)
        all_ape.append(ape_score)
        all_accuracy.append(accuracy_score)
        all_energy_accuracy.append(energy_acc) # Append energy accuracy


    return all_maeScore, all_SAE, all_f1s, all_nde, all_classification_accuracy, all_ape, all_accuracy, all_energy_accuracy # Return energy accuracy list

def evaluateResult(nets, config, vali_Dataloader, DEVICE, mode=-1):
    """
    Evaluates the model and prints the results.
    """
    y_vali_pred, y_vali, y_vali_ori, y_vali_pred_c, y_vali_ori_c, truex = predict(nets, config, vali_Dataloader, DEVICE, mode=mode)

    y_vali_pred = y_vali_pred.reshape(-1,y_vali_pred.shape[-1])
    y_vali_pred_c = y_vali_pred_c.reshape(-1,y_vali_pred.shape[-1])
    y_vali_ori = y_vali_ori.reshape(-1,y_vali_pred.shape[-1])
    y_vali_ori_c = y_vali_ori_c.reshape(-1,y_vali_pred.shape[-1])
    y_vali_pred[y_vali_pred < 0] = 0
    y_vali_pred_d = y_vali_pred * 612
    y_vali_pred_d_update = y_vali_pred_d

    y_p = y_vali_pred_c
    y_p[y_p >= 0.5]=1
    y_p[y_p<0.5]=0
    y_vali_pred_d_update=y_vali_pred_d_update*y_p

    if mode >= 0:
        maeScore, SAE, f1s, classification_accuracy, nde_score, ape_score, accuracy_score, energy_acc = evaluate_score( # Unpack energy accuracy
            y_vali_ori.numpy(),
            y_vali_pred_d_update.numpy(),
            y_vali_ori_c.numpy(),
            y_vali_pred_c.numpy(),
        )
        print(f"Classification Accuracy: {classification_accuracy:.2f}%")
        print(f"Accuracy (100 - APE): {accuracy_score:.2f}%")
        print(f"Energy Accuracy: {energy_acc:.2f}%") # Print energy accuracy

    else:
        maeScore, SAE, f1s, nde_scores, all_classification_accuracy, all_ape, all_accuracy, all_energy_accuracy = evaluate_score_multi( # Unpack energy accuracy list
            y_vali_ori.numpy(),
            y_vali_pred_d_update.numpy(),
            y_vali_ori_c.numpy(),
            y_vali_pred_c.numpy(),
        )
        #for i, appliance in enumerate(listOfAppliance):
            #print(f"{appliance} Accuracy: {all_classification_accuracy[i]:.2f}%")


    return maeScore, SAE, f1s, nde_scores, all_classification_accuracy, all_ape, all_accuracy, all_energy_accuracy, y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, y_vali_pred_c, truex.reshape(-1, 1) # Return energy accuracy list

def predict(t_nets, t_cfg, vali_Dataloader, DEVICE, mode=-1):
    '''
    :param t_net: pa_rnn_net(encoder, decoder, encoder_optimizer, decoder_optimizer)
    :param t_dat: data include train and evaluation and test.
    :param t_cfg: config file for train
    :param on_train: when on_train, predict will evaluate the result using train sample, otherwise, use test sample
    :return: y_pred:
    '''
    y_pred_r = []  # (test_size)
    y_true_scaled_r = []
    y_true_r = []
    y_pred_c = []  # (test_size)
    y_true_c = []
    x_true = []
    start = int((t_cfg["inputLength"]-t_cfg["outputLength"])/2)
    end = start + t_cfg["outputLength"]

    with torch.no_grad():
        for _, (X, Y, X_scaled, Y_scaled, Y_of) in enumerate(vali_Dataloader):
            if mode>=0:
                Y = Y[:,start:end,[mode]]
                Y_scaled = Y_scaled[:,start:end,[mode]]
                Y_of = Y_of[:,start:end,[mode]]
            else:
                Y = Y[:,start:end,:]
                Y_scaled = Y_scaled[:,start:end,:]
                Y_of = Y_of[:,start:end,:]

            X_scaled = X_scaled.float().to(DEVICE)
            Y_scaled = Y_scaled.float().to(DEVICE)
            Y = Y.float().to(DEVICE)
            Y_of = Y_of.float().to(DEVICE)

            output_r=0
            output_c=0

            for t_net in t_nets:
              output_r_t, output_c_t = t_net(X_scaled)
              output_r += output_r_t
              output_c += output_c_t
            output_r = output_r/len(t_nets)
            output_c = output_c/len(t_nets)

            print(output_r.shape)
            y_pred_r.append(output_r.cpu())
            y_true_scaled_r.append(Y_scaled.cpu())
            y_true_r.append(Y.cpu())
            x_true.append(X[:,start:end,:])

            y_pred_c.append(output_c.cpu())
            y_true_c.append(Y_of.cpu())

        out_pred_scaled_r = torch.vstack(y_pred_r)
        out_true_scaled_r = torch.vstack(y_true_scaled_r)
        out_true_r = torch.vstack(y_true_r)
        out_true_x = torch.vstack(x_true)
        out_pred_scaled_c = torch.vstack(y_pred_c)
        out_true_c = torch.vstack(y_true_c)

    return out_pred_scaled_r, out_true_scaled_r, out_true_r, out_pred_scaled_c, out_true_c, out_true_x

if __name__ == '__main__':
    set_random_state(2024)

    ###################################################################################
    # define configs
    config_dict = {
        "input_size": 3,
        "batch_size": 32, #batch size
        "lr": 0.0001, #learning rate
        "hidden":64, #encoder decoder hidden size
        "dropout": 0.1, #dropout
        "outputLength": 864, #output length for the model
        "inputLength" : 864, #input length for the model
        "dataAug": True,
        "prob0": 0.3, #augment probability for Dishwasher
        "prob1": 0.3,
        "prob2": 0.3,
        "prob3": 0.3,

        'weight_saving_path': './weights/test_run/',
        "epochs": 1000,
        "num_workers": 2, #cpu core
        "debug": True,
        'perform_dataAug': True,
    }
    DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    ###################################################################################
    # define datasets and dataloader
    path = "/content/drive/MyDrive/Data/All_Hardware_xlsx"
    #train_arrays = pkl.load(open(os.path.join(path,"train_small.pkl"),'rb'))
    #val_arrays = pkl.load(open(os.path.join(path,"val_small.pkl"),'rb'))
    test_arrays = pkl.load(open(os.path.join(path,"New_Hardware_test.pkl"),'rb'))

    length_input = config_dict["inputLength"]
    length_output = config_dict["outputLength"]

    # ListTrain = [SubSet(array.values, length_input=length_input, length_output=length_output) for array in train_arrays]
    # ListVal = [SubSet(array.values, length_input=length_input, length_output=length_output) for array in val_arrays]
    ListTest = [SubSet(array.values, length_input=length_input, length_output=length_output) for array in [test_arrays]]

    # train_dataset = ConcatDataset(ListTrain)
    # val_dataset = ConcatDataset(ListVal)
    test_dataset = ConcatDataset(ListTest)

    # index = np.arange(0,train_dataset.cumulative_sizes[-1])
    # train_subsampler = torch.utils.data.SubsetRandomSampler(index)
    # train_Dataloader = DataLoader(
    #     train_dataset,
    #     batch_size=config_dict["batch_size"],
    #     sampler=train_subsampler,
    #     num_workers=config_dict["num_workers"],
    #     pin_memory=True)

    # sampler = testSampler(val_dataset.cumulative_sizes[-1], config_dict["outputLength"])
    sampler_test = testSampler(test_dataset.cumulative_sizes[-1], config_dict["outputLength"])
    print(sampler_test)
    # vali_Dataloader = DataLoader(
    #     val_dataset,
    #     batch_size=config_dict["batch_size"],
    #     sampler=sampler,
    #     num_workers=config_dict["num_workers"],
    #     pin_memory=True)

    test_Dataloader = DataLoader(
        test_dataset,
        batch_size=config_dict["batch_size"],
        sampler=sampler_test,
        num_workers=config_dict["num_workers"],
        pin_memory=True)

    ###################################################################################
    # define model
    models=[]
    paths=[
       # '/content/drive/MyDrive/Data/checkpoint_best_loss_part1.pth',
        #   '/content/drive/MyDrive/Data/checkpoint_best_loss_part2.pth',
           '/content/drive/MyDrive/Data/checkpoint_best_loss_part3.pth',
          '/content/drive/MyDrive/Data/checkpoint_best_loss_0.68.pth',
         #  '/content/drive/MyDrive/Data/checkpoint_best_loss_part5.pth'
        ]
    for path in paths:
        model = MATconv(config_dict).to(DEVICE)
        checkpoint_path = path
        print('loading checkpoint!')
        checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))
        #checkpoint = torch.load(checkpoint_path)
        print('loss score: {:.4f}'.format(checkpoint['val_loss']))
        model.load_state_dict(checkpoint['Model_state_dict'])
        model.eval()
        models.append(model)
        del model

    # check results
    maeScore, SAE, f1s, nde_scores, all_classification_accuracy, all_ape, all_accuracy, all_energy_accuracy, y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, y_vali_pred_c, truex = evaluateResult(models, config_dict, test_Dataloader, DEVICE, mode=-1)
    print(y_vali_pred_d_update)
    listOfAppliance = ['dish washer', 'fridge', 'microwave', 'wash']
    listOfAppliance_dict = {0:'M1', 1:'M2', 2:'M3', 3:'M4'}
    listOfAppliance_dict_value = {'M1':[], 'M2':[], 'M3':[], 'M4':[]}
    for i in range(4):
        listOfAppliance_dict_value[listOfAppliance_dict[i]] = [maeScore[i], SAE[i], f1s[i], nde_scores[i], all_accuracy[i], all_energy_accuracy[i]]
    listOfAppliance_dict_value.update({'Metric':['MAE', 'SAE', 'F1', 'NDE', 'Accuracy (100-APE)', 'Energy Accuracy']})
    listOfAppliance_dict_value.update({'Avg':[np.mean(maeScore), np.mean(SAE), np.mean(f1s), np.mean(nde_scores), np.mean(all_accuracy), np.mean(all_energy_accuracy)]})

    df = pd.DataFrame(listOfAppliance_dict_value)
    df = df.set_index('Metric')
    print(df)

import numpy as np
import matplotlib.pyplot as plt

def calculate_mae_for_num_machines_on(y_vali_ori, y_vali_ori_c, y_vali_pred_d_update, num_machines_on):
    """Calculates the MAE for a specific number of machines being on."""
    indices = np.where(y_vali_ori_c.sum(axis=1) == num_machines_on)
    mae = np.abs(y_vali_ori[indices] - y_vali_pred_d_update[indices]).mean()
    return mae

# Calculate MAE for different numbers of machines on
num_machines_on_list = range(5)  # 0 to 4 machines
mae_scores = []
for num_machines_on in num_machines_on_list:
    mae = calculate_mae_for_num_machines_on(y_vali_ori, y_vali_ori_c, y_vali_pred_d_update, num_machines_on)
    mae_scores.append(mae)

# Plotting
plt.figure(figsize=(8, 6))
plt.bar(num_machines_on_list, mae_scores)
plt.xlabel("Number of Machines On")
plt.ylabel("MAE Score")
plt.title("MAE vs. Number of Machines On")
plt.xticks(num_machines_on_list)  # Set x-axis ticks to 0, 1, 2, 3, 4
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Assuming the 'nde' function is already defined in a previous cell
# from . import nde # Uncomment and modify if needed based on your notebook structure

def calculate_nde_for_num_machines_on(y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, num_machines_on):
    """Calculates the NDE for a specific number of machines being on."""
    # Convert inputs to numpy arrays if they are tensors
    y_vali_ori_np = y_vali_ori.numpy() if isinstance(y_vali_ori, torch.Tensor) else np.asarray(y_vali_ori)
    y_vali_pred_d_update_np = y_vali_pred_d_update.numpy() if isinstance(y_vali_pred_d_update, torch.Tensor) else np.asarray(y_vali_pred_d_update)
    y_vali_ori_c_np = y_vali_ori_c.numpy() if isinstance(y_vali_ori_c, torch.Tensor) else np.asarray(y_vali_ori_c)

    indices = np.where(y_vali_ori_c_np.sum(axis=1) == num_machines_on)
    y_true = y_vali_ori_np[indices].flatten()
    y_pred = y_vali_pred_d_update_np[indices].flatten()
    nde_score = nde(y_true, y_pred)
    return nde_score

# Calculate NDE for different numbers of machines on
num_machines_on_list = range(5)  # 0 to 4 machines
nde_scores = []
# Assuming y_vali_ori, y_vali_pred_d_update, and y_vali_ori_c are already defined and available
for num_machines_on in num_machines_on_list:
    nde_score = calculate_nde_for_num_machines_on(y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, num_machines_on)
    nde_scores.append(nde_score)

# Plotting
plt.figure(figsize=(8, 6))
plt.bar(num_machines_on_list, nde_scores)
plt.xlabel("Number of Machines On")
plt.ylabel("NDE Score")
plt.title("NDE vs. Number of Machines On")
plt.xticks(num_machines_on_list)  # Set x-axis ticks to 0, 1, 2, 3, 4
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score

def calculate_f1_for_num_machines_on(y_vali_ori_c, y_vali_pred_c, num_machines_on):
    """Calculates the F1 score for a specific number of machines being on."""
    indices = np.where(y_vali_ori_c.sum(axis=1) == num_machines_on)
    # Select the relevant data based on indices
    y_true = y_vali_ori_c[indices].flatten()
    y_pred = y_vali_pred_c[indices].flatten()
    # Calculate F1 score. Use zero_division=0 to avoid warnings if a class has no predictions
    f1 = f1_score(y_true, y_pred, zero_division=0)
    return f1

# Calculate F1 score for different numbers of machines on
num_machines_on_list = range(5)  # 0 to 4 machines
f1_scores = []
# Assume y_vali_ori_c and y_vali_pred_c_update are already defined and available
# y_vali_ori_c: True classification labels (binary: 0 or 1)
# y_vali_pred_c_update: Predicted classification labels (binary: 0 or 1)
for num_machines_on in num_machines_on_list:
    f1 = calculate_f1_for_num_machines_on(y_vali_ori_c, y_vali_pred_c, num_machines_on)
    f1_scores.append(f1)

# Plotting
plt.figure(figsize=(8, 6))
plt.bar(num_machines_on_list, f1_scores)
plt.xlabel("Number of Machines On")
plt.ylabel("F1 Score")
plt.title("F1 Score vs. Number of Machines On")
plt.xticks(num_machines_on_list)  # Set x-axis ticks to 0, 1, 2, 3, 4
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Assuming the 'sae' function is already defined in a previous cell
# from . import sae # Uncomment and modify if needed based on your notebook structure

def calculate_sae_for_num_machines_on(y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, num_machines_on):
    """Calculates the SAE for a specific number of machines being on."""
    # Convert inputs to numpy arrays if they are tensors
    y_vali_ori_np = y_vali_ori.numpy() if isinstance(y_vali_ori, torch.Tensor) else np.asarray(y_vali_ori)
    y_vali_pred_d_update_np = y_vali_pred_d_update.numpy() if isinstance(y_vali_pred_d_update, torch.Tensor) else np.asarray(y_vali_pred_d_update)
    y_vali_ori_c_np = y_vali_ori_c.numpy() if isinstance(y_vali_ori_c, torch.Tensor) else np.asarray(y_vali_ori_c)

    indices = np.where(y_vali_ori_c_np.sum(axis=1) == num_machines_on)
    y_true = y_vali_ori_np[indices].flatten()
    y_pred = y_vali_pred_d_update_np[indices].flatten()
    sae_score = sae(y_true, y_pred, 1200) # Assuming N = 1200 for SAE calculation
    return sae_score

# Calculate SAE for different numbers of machines on
num_machines_on_list = range(5)  # 0 to 4 machines
sae_scores = []
# Assuming y_vali_ori, y_vali_pred_d_update, and y_vali_ori_c are already defined and available
for num_machines_on in num_machines_on_list:
    sae_score = calculate_sae_for_num_machines_on(y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, num_machines_on)
    sae_scores.append(sae_score)

# Plotting
plt.figure(figsize=(8, 6))
plt.bar(num_machines_on_list, sae_scores)
plt.xlabel("Number of Machines On")
plt.ylabel("SAE Score")
plt.title("SAE vs. Number of Machines On")
plt.xticks(num_machines_on_list)  # Set x-axis ticks to 0, 1, 2, 3, 4
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import f1_score

# Assuming the 'nde', 'sae', 'ape', 'energy_accuracy', 'calculate_mae_for_num_machines_on',
# 'calculate_sae_for_num_machines_on', 'calculate_f1_for_num_machines_on', and
# 'calculate_nde_for_num_machines_on' functions are already defined in previous cells.

def nde(true, pred):
    """Calculates the Normalized Disaggregation Error (NDE)."""
    # Convert inputs to numpy arrays if they are tensors
    true_np = true.numpy() if isinstance(true, torch.Tensor) else np.asarray(true)
    pred_np = pred.numpy() if isinstance(pred, torch.Tensor) else np.asarray(pred)

    numerator = np.sqrt(np.sum((true_np - pred_np)**2))
    denominator = np.sqrt(np.sum(true_np**2))
    return numerator / denominator if denominator != 0 else np.nan


def sae(true, pred, N):
    """Calculates the Static Aggregation Error (SAE)."""
    # Convert inputs to numpy arrays if they are tensors
    true_np = true.numpy() if isinstance(true, torch.Tensor) else np.asarray(true)
    pred_np = pred.numpy() if isinstance(pred, torch.Tensor) else np.asarray(pred)

    num_period = int(len(true_np) / N)
    diff = 0
    for i in range(num_period):
        diff += abs(np.sum(true_np[i * N: (i + 1) * N]) - np.sum(pred_np[i * N: (i + 1) * N]))
    return diff / (N * num_period)

def ape(true, pred):
    """Calculates the Absolute Percentage Error (APE) with handling for zero true values and capping."""
    # Convert inputs to numpy arrays if they are tensors
    true_np = true.numpy() if isinstance(true, torch.Tensor) else np.asarray(true)
    pred_np = pred.numpy() if isinstance(pred, torch.Tensor) else np.asarray(pred)

    # Calculate individual APE values
    individual_ape = np.zeros_like(true_np, dtype=float)
    non_zero_indices = true_np != 0
    zero_indices = true_np == 0

    # Calculate APE for non-zero true values
    individual_ape[non_zero_indices] = (np.abs(true_np[non_zero_indices] - pred_np[non_zero_indices]) / true_np[non_zero_indices]) * 100

    # Calculate APE for zero true values
    individual_ape[zero_indices] = np.abs(true_np[zero_indices] - pred_np[zero_indices]) * 100 # As per user's formula

    # Cap APE values at 150 if they exceed 200
    individual_ape[individual_ape > 200] = 150

    # Calculate the mean APE
    ape_score = np.mean(individual_ape)

    return ape_score

def energy_accuracy(true_values, pred_values, spike_threshold=50):
    """Calculates the Energy Accuracy, ignoring abnormal spikes."""
    true_np = np.array(true_values, dtype=float)
    pred_np = np.array(pred_values, dtype=float)

    # Handle abnormal spikes: if a true value is > spike_threshold × median(true),
    # treat it as abnormal and ignore it in accuracy calculation
    median_val = np.median(true_np[true_np > 0]) if np.any(true_np > 0) else 1
    spike_mask = true_np > (spike_threshold * median_val)

    # Mask for normal data points
    normal_mask = ~spike_mask

    # Total actual energy for normal points
    total_true = np.sum(true_np[normal_mask])

    if total_true == 0:
        return 0.0  # Avoid division by zero if no valid data

    # Absolute error sum
    total_error = np.sum(np.abs(true_np[normal_mask] - pred_np[normal_mask]))

    # Energy Accuracy
    accuracy = (1 - (total_error / total_true)) * 100

    return accuracy

def calculate_mae_for_num_machines_on(y_vali_ori, y_vali_ori_c, y_vali_pred_d_update, num_machines_on):
    """Calculates the MAE for a specific number of machines being on."""
    # Convert inputs to numpy arrays if they are tensors
    y_vali_ori_np = y_vali_ori.numpy() if isinstance(y_vali_ori, torch.Tensor) else np.asarray(y_vali_ori)
    y_vali_pred_d_update_np = y_vali_pred_d_update.numpy() if isinstance(y_vali_pred_d_update, torch.Tensor) else np.asarray(y_vali_pred_d_update)
    y_vali_ori_c_np = y_vali_ori_c.numpy() if isinstance(y_vali_ori_c, torch.Tensor) else np.asarray(y_vali_ori_c)

    indices = np.where(y_vali_ori_c_np.sum(axis=1) == num_machines_on)
    mae = np.abs(y_vali_ori_np[indices] - y_vali_pred_d_update_np[indices]).mean()
    return mae

def calculate_nde_for_num_machines_on(y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, num_machines_on):
    """Calculates the NDE for a specific number of machines being on."""
    # Convert inputs to numpy arrays if they are tensors
    y_vali_ori_np = y_vali_ori.numpy() if isinstance(y_vali_ori, torch.Tensor) else np.asarray(y_vali_ori)
    y_vali_pred_d_update_np = y_vali_pred_d_update.numpy() if isinstance(y_vali_pred_d_update, torch.Tensor) else np.asarray(y_vali_pred_d_update)
    y_vali_ori_c_np = y_vali_ori_c.numpy() if isinstance(y_vali_ori_c, torch.Tensor) else np.asarray(y_vali_ori_c)


    indices = np.where(y_vali_ori_c_np.sum(axis=1) == num_machines_on)
    y_true = y_vali_ori_np[indices].flatten()
    y_pred = y_vali_pred_d_update_np[indices].flatten()
    nde_score = nde(y_true, y_pred)
    return nde_score

def calculate_sae_for_num_machines_on(y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, num_machines_on):
    """Calculates the SAE for a specific number of machines being on."""
    # Convert inputs to numpy arrays if they are tensors
    y_vali_ori_np = y_vali_ori.numpy() if isinstance(y_vali_ori, torch.Tensor) else np.asarray(y_vali_ori)
    y_vali_pred_d_update_np = y_vali_pred_d_update.numpy() if isinstance(y_vali_pred_d_update, torch.Tensor) else np.asarray(y_vali_pred_d_update)
    y_vali_ori_c_np = y_vali_ori_c.numpy() if isinstance(y_vali_ori_c, torch.Tensor) else np.asarray(y_vali_ori_c)

    indices = np.where(y_vali_ori_c_np.sum(axis=1) == num_machines_on)
    y_true = y_vali_ori_np[indices].flatten()
    y_pred = y_vali_pred_d_update_np[indices].flatten()
    sae_score = sae(y_true, y_pred, 1200) # Assuming N = 1200 for SAE calculation
    return sae_score


def calculate_f1_for_num_machines_on(y_vali_ori_c, y_vali_pred_c, num_machines_on):
    """Calculates the F1 score for a specific number of machines being on."""
    # Convert inputs to numpy arrays if they are tensors
    y_vali_ori_c_np = y_vali_ori_c.numpy() if isinstance(y_vali_ori_c, torch.Tensor) else np.asarray(y_vali_ori_c)
    y_vali_pred_c_np = y_vali_pred_c.numpy() if isinstance(y_vali_pred_c, torch.Tensor) else np.asarray(y_vali_pred_c)

    indices = np.where(y_vali_ori_c_np.sum(axis=1) == num_machines_on)
    # Select the relevant data based on indices
    y_true = y_vali_ori_c_np[indices].flatten()
    y_pred = y_vali_pred_c_np[indices].flatten().round() # Round predictions to binary for F1
    # Calculate F1 score. Use zero_division=0 to avoid warnings if a class has no predictions
    f1 = f1_score(y_true, y_pred, zero_division=0)
    return f1


# Calculate scores for different numbers of machines on
num_machines_on_list = range(5)  # 0 to 4 machines
mae_scores = []
sae_scores = []
f1_scores = []
nde_scores = []


# Assuming y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, and y_vali_pred_c
# are already defined and available from previous cells.
for num_machines_on in num_machines_on_list:
    mae = calculate_mae_for_num_machines_on(y_vali_ori, y_vali_ori_c, y_vali_pred_d_update, num_machines_on)
    mae_scores.append(mae)

    sae_score = calculate_sae_for_num_machines_on(y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, num_machines_on)
    sae_scores.append(sae_score)

    f1 = calculate_f1_for_num_machines_on(y_vali_ori_c, y_vali_pred_c, num_machines_on)
    f1_scores.append(f1)

    nde_score = calculate_nde_for_num_machines_on(y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, num_machines_on)
    nde_scores.append(nde_score)


# Plotting
fig, axes = plt.subplots(2, 2, figsize=(12, 10)) # 2 rows, 2 columns for the four plots

# Plot MAE scores
axes[0, 0].bar(num_machines_on_list, mae_scores)
axes[0, 0].set_xlabel("Number of Machines On")
axes[0, 0].set_ylabel("MAE Score")
axes[0, 0].set_title("MAE vs. Number of Machines On")
axes[0, 0].set_xticks(num_machines_on_list)
axes[0, 0].grid(True)

# Plot SAE scores
axes[0, 1].bar(num_machines_on_list, sae_scores)
axes[0, 1].set_xlabel("Number of Machines On")
axes[0, 1].set_ylabel("SAE Score")
axes[0, 1].set_title("SAE vs. Number of Machines On")
axes[0, 1].set_xticks(num_machines_on_list)
axes[0, 1].grid(True)

# Plot F1 scores
axes[1, 0].bar(num_machines_on_list, f1_scores)
axes[1, 0].set_xlabel("Number of Machines On")
axes[1, 0].set_ylabel("F1 Score")
axes[1, 0].set_title("F1 Score vs. Number of Machines On")
axes[1, 0].set_xticks(num_machines_on_list)
axes[1, 0].grid(True)

# Plot NDE scores
axes[1, 1].bar(num_machines_on_list, nde_scores)
axes[1, 1].set_xlabel("Number of Machines On")
axes[1, 1].set_ylabel("NDE Score")
axes[1, 1].set_title("NDE vs. Number of Machines On")
axes[1, 1].set_xticks(num_machines_on_list)
axes[1, 1].grid(True)

plt.tight_layout() # Adjust layout for better spacing
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import torch
from sklearn.metrics import f1_score

# Assuming y_vali_ori, y_vali_pred_d_update, and y_vali_ori_c are available
# and the metric calculation functions (mae, sae, ape, f1_score) are defined in previous cells.

def sae(true, pred, N):
    """Calculates the Static Aggregation Error (SAE)."""
    # Convert inputs to numpy arrays if they are tensors
    true_np = true.numpy() if isinstance(true, torch.Tensor) else np.asarray(true)
    pred_np = pred.numpy() if isinstance(pred, torch.Tensor) else np.asarray(pred)

    num_period = int(len(true_np) / N)
    diff = 0
    for i in range(num_period):
        diff += abs(np.sum(true_np[i * N: (i + 1) * N]) - np.sum(pred_np[i * N: (i + 1) * N]))
    return diff / (N * num_period)

def ape(true, pred):
    """Calculates the Absolute Percentage Error (APE) with handling for zero true values and capping."""
    # Convert inputs to numpy arrays if they are tensors
    true_np = true.numpy() if isinstance(true, torch.Tensor) else np.asarray(true)
    pred_np = pred.numpy() if isinstance(pred, torch.Tensor) else np.asarray(pred)

    # Calculate individual APE values
    individual_ape = np.zeros_like(true_np, dtype=float)
    non_zero_indices = true_np != 0
    zero_indices = true_np == 0

    # Calculate APE for non-zero true values
    individual_ape[non_zero_indices] = (np.abs(true_np[non_zero_indices] - pred_np[non_zero_indices]) / true_np[non_zero_indices]) * 100

    # Calculate APE for zero true values
    individual_ape[zero_indices] = np.abs(true_np[zero_indices] - pred_np[zero_indices]) * 100 # As per user's formula

    # Cap APE values at 150 if they exceed 200
    individual_ape[individual_ape > 200] = 150

    # Calculate the mean APE
    ape_score = np.mean(individual_ape)

    return ape_score

def energy_accuracy(true_values, pred_values, spike_threshold=50):
    """Calculates the Energy Accuracy, ignoring abnormal spikes."""
    true_np = np.array(true_values, dtype=float)
    pred_np = np.array(pred_values, dtype=float)

    # Handle abnormal spikes: if a true value is > spike_threshold × median(true),
    # treat it as abnormal and ignore it in accuracy calculation
    median_val = np.median(true_np[true_np > 0]) if np.any(true_np > 0) else 1
    spike_mask = true_np > (spike_threshold * median_val)

    # Mask for normal data points
    normal_mask = ~spike_mask

    # Total actual energy for normal points
    total_true = np.sum(true_np[normal_mask])

    if total_true == 0:
        return 0.0  # Avoid division by zero if no valid data

    # Absolute error sum
    total_error = np.sum(np.abs(true_np[normal_mask] - pred_np[normal_mask]))

    # Energy Accuracy
    accuracy = (1 - (total_error / total_true)) * 100

    return accuracy

def nde(true, pred):
    """Calculates the Normalized Disaggregation Error (NDE)."""
    # Convert inputs to numpy arrays if they are tensors
    true_np = true.numpy() if isinstance(true, torch.Tensor) else np.asarray(true)
    pred_np = pred.numpy() if isinstance(pred, torch.Tensor) else np.asarray(pred)

    numerator = np.sqrt(np.sum((true_np - pred_np)**2))
    denominator = np.sqrt(np.sum(true_np**2))
    return numerator / denominator if denominator != 0 else np.nan


# Define appliance names
listOfAppliance = ['L1', 'L2', 'L3', 'L4']

# Initialize dictionaries to store metrics for on and off states
mae_on = {}
mae_off = {}
sae_on = {}
sae_off = {}
f1_on = {}
f1_off = {}
nde_on = {} # Added NDE for on state
nde_off = {} # Added NDE for off state


# Iterate through each appliance (column in y_vali_ori and y_vali_ori_c)
for i in range(y_vali_ori.shape[1]):
    appliance_name = listOfAppliance[i]

    # Convert tensors to numpy arrays for calculations
    actual_power = y_vali_ori[:, i].numpy()
    predicted_power = y_vali_pred_d_update[:, i].numpy()
    actual_on_off = y_vali_ori_c[:, i].numpy()
    predicted_on_off = y_vali_pred_c[:, i].numpy()


    # Indices where the appliance is ON in the actual data
    on_indices = np.where(actual_on_off == 1)[0]

    # Indices where the appliance is OFF in the actual data
    off_indices = np.where(actual_on_off == 0)[0]

    # Calculate MAE for ON state
    if len(on_indices) > 0:
        mae_on[appliance_name] = np.abs(actual_power[on_indices] - predicted_power[on_indices]).mean()
        # Calculate SAE for ON state (adjust N if needed)
        sae_on[appliance_name] = sae(actual_power[on_indices], predicted_power[on_indices], N=1200)
        # Calculate F1 for ON state
        f1_on[appliance_name] = f1_score(actual_on_off[on_indices], np.round(predicted_on_off[on_indices]), zero_division=0)
        # Calculate NDE for ON state
        nde_on[appliance_name] = nde(actual_power[on_indices], predicted_power[on_indices])


    else:
        mae_on[appliance_name] = 0.0
        sae_on[appliance_name] = 0.0
        f1_on[appliance_name] = 0.0
        nde_on[appliance_name] = np.nan # NDE is undefined for zero true values

    # Calculate MAE for OFF state
    if len(off_indices) > 0:
        mae_off[appliance_name] = np.abs(actual_power[off_indices] - predicted_power[off_indices]).mean()
         # Calculate SAE for OFF state (adjust N if needed)
        sae_off[appliance_name] = sae(actual_power[off_indices], predicted_power[off_indices], N=1200)
         # Calculate F1 for OFF state
        f1_off[appliance_name] = f1_score(actual_on_off[off_indices], np.round(predicted_on_off[off_indices]), zero_division=0)
        # Calculate NDE for OFF state
        nde_off[appliance_name] = nde(actual_power[off_indices], predicted_power[off_indices])

    else:
        mae_off[appliance_name] = 0.0
        sae_off[appliance_name] = 0.0
        f1_off[appliance_name] = 0.0
        nde_off[appliance_name] = np.nan # NDE is undefined for zero true values


# Prepare data for plotting
metrics_on = [mae_on, sae_on, f1_on, nde_on] # Changed to include NDE
metrics_off = [mae_off, sae_off, f1_off, nde_off] # Changed to include NDE
metric_names = ['MAE', 'SAE', 'F1 Score', 'NDE'] # Changed to include NDE

# Plotting
fig, axes = plt.subplots(2, 2, figsize=(15, 10)) # 2x2 grid for 4 metrics
axes = axes.flatten() # Flatten the 2x2 array of axes for easy iteration

x = np.arange(len(listOfAppliance)) # the label locations
width = 0.35 # the width of the bars

for i in range(len(metric_names)):
    on_scores = [metrics_on[i][app] for app in listOfAppliance]
    off_scores = [metrics_off[i][app] for app in listOfAppliance]

    rects1 = axes[i].bar(x - width/2, on_scores, width, label='On')
    rects2 = axes[i].bar(x + width/2, off_scores, width, label='Off')

    # Add some text for labels, title and custom x-axis tick labels, etc.
    axes[i].set_ylabel(metric_names[i])
    axes[i].set_title(f'{metric_names[i]} by Machine On/Off State')
    axes[i].set_xticks(x)
    axes[i].set_xticklabels(listOfAppliance)
    axes[i].legend()
    axes[i].grid(True, axis='y')

plt.tight_layout()
plt.show()

"""PLOTTING

"""

import matplotlib.pyplot as plt
import numpy as np
import torch
from torch.utils.data import DataLoader, ConcatDataset
import os
import pickle as pkl
#from datasets import SubSet, testSampler
#from models import MATconv as MAT

#from trainer_callbacks import set_random_state
#Assuming the functions evaluateResult, predict, evaluate_score_multi, evaluate_score and sae are defined in your notebook

# ... (your existing code for defining datasets, model, etc.) ...

# Load the test data
path = "/content/drive/MyDrive/Data/All_Hardware_xlsx"
test_arrays = pkl.load(open(os.path.join(path, "New_Hardware_test.pkl"), 'rb')) # Assuming the correct test file is New_Hardware_test.pkl
ListTest = [SubSet(array.values, length_input=config_dict["inputLength"], length_output=config_dict["outputLength"]) for array in [test_arrays]]
test_dataset = ConcatDataset(ListTest)
sampler_test = testSampler(test_dataset.cumulative_sizes[-1], config_dict["outputLength"])
test_Dataloader = DataLoader(test_dataset, batch_size=config_dict["batch_size"], sampler=sampler_test, num_workers=config_dict["num_workers"], pin_memory=True)

# Assuming 'model' and 'config_dict' and 'DEVICE' are already defined from previous cells.
# If you are running this cell independently, you might need to re-define them or load a saved model.

# Get the predictions
# Assuming evaluateResult function and its dependencies are defined in previous cells
maeScore, SAE, f1s, nde_scores, all_classification_accuracy, all_ape, all_accuracy, all_energy_accuracy, y_vali_ori, y_vali_pred_d_update, y_vali_ori_c, y_vali_pred_c, truex = evaluateResult(
    models, config_dict, test_Dataloader, DEVICE, mode=-1  # Set mode to -1 for all appliances
)


# Plot the actual and predicted data for each appliance in a single figure
# Assuming y_vali_ori and y_vali_pred_d_update are available from the evaluateResult function call
listOfAppliance = ['L1', 'L2', 'L3', 'L4'] # Changed to reflect appliance names

fig, axes = plt.subplots(4, 1, figsize=(12, 16)) # 4 rows, 1 column for four appliances

for i in range(y_vali_pred_d_update.shape[1]):
    axes[i].plot(y_vali_ori[:, i], label='Actual')
    axes[i].plot(y_vali_pred_d_update[:, i], label='Predicted')
    axes[i].set_xlabel('Time')
    axes[i].set_ylabel('Power Consumption')
    axes[i].set_title(f'Actual vs. Predicted Power Consumption - {listOfAppliance[i]}')
    axes[i].legend()
    axes[i].grid(True)

plt.tight_layout() # Adjust layout for better spacing
plt.show()